template = "https://github.com/giellalt/template-lang-und"
rev_id = 269
template_sha = "c43b39fe5507de4cc3a96e60743ab44578e61fd2"

[replacements]
__GLOTTOLOG_ID__ = "amha1245"
__REPO__ = "lang-amh"
__UND2C__ = "am"
__UNDEFINED__ = "Amharic"
__UND__ = "amh"
